### ISSUE TITLE
Add new instruction to run 'pdf.s' 

### ISSUE THREAD

**Issue by EZePiZy** [RISC-V-IAC/RISC-V-CPU#19]
Instructions to add: 

- sb: Require adding control signals + changing the data memory unit (allow accessing bytes in words) 
- lui: U2-Type instruction; allow fetching upper-immediate and concatenate with 12'b0
- lbu: Require adding a ZeroExtend unit in the data memory 
- and: Allow us to do bitwise and operation (useful for trigger program)

**Comment by luigirinaldi** [comment]
Addressed in [ed135e1](https://github.com/EZePiZy/RISC-V-CPU/commit/ed135e1f9ad6f265f97075c073fed178ec5794ae)
